---
# control
control:
  data_name: GUE
  task_name: mouse
  subset: Ch12Nrf2Iggrab-Ch12Znf384hpa004051Iggrab # TODO: add multiple datasets
  model_name: dnabert2
# experiment
pin_memory: True
num_workers: 0
init_seed: 0
num_experiments: 1
log_interval: 0.25
device: cuda
resume_mode: 0
profile: False