---
# control
control:
  data_name: GUE
  task_name: EMP
  subset_name: H3~H3K4me1
  model_name: dnabert2
#  model_name: Qwen2.5-0.5B-Instruct
  freeze: 0
  embedding_mode: word  # index
# experiment
pin_memory: True
num_workers: 0
init_seed: 0
num_experiments: 1
log_interval: 0.25
device: cuda
resume_mode: 0
profile: False