---
# control
control:
  data_name: GUE
  task_name: mouse
  subset_name: all
  model_name: dnabert2
  freeze: 1
  embedding_mode: index
  # TODO add freeze and embedding index
# experiment
pin_memory: True
num_workers: 0
init_seed: 0
num_experiments: 1
log_interval: 0.25
device: cuda
resume_mode: 0
profile: False